#pragma kernel Emit



RWStructuredBuffer<float3> _PositionList;

StructuredBuffer<uint> _Counter;
ConsumeStructuredBuffer<uint> _DeadConsumeList;
AppendStructuredBuffer<uint> _AliveAppendList;

StructuredBuffer<float3> _UploadPositionList;


[numthreads(1,1,1)]
void Emit (uint3 id : SV_DispatchThreadID) {
	uint i = id.x;
	if (i < _Counter[0]) {
		uint j = _DeadConsumeList.Consume();
		_PositionList[j] = _UploadPositionList[i];
		_AliveAppendList.Append(j);
	}
}
